# Generated by Django 4.1.3 on 2022-11-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_games.game')),
            ],
            options={
                'verbose_name_plural': 'gamers',
            },
        ),
    ]
